answers: # this needs to match the profile: in your dbt_project.yml file
  target: dev  # The default for any dbt commands
  outputs:
    dev:
      type: bigquery
      method: oauth
      database: "dbt-sajana"
      schema: dbt_test
      threads: 64
      timeout_seconds: 300
      location: US
      priority: interactive
      job_retry: None  # <-- Make sure this line is here and correctly indented

    production:
      type: bigquery
      method: oauth
      database: "dbt-sajana"
      schema: dbt_production
      threads: 64
      timeout_seconds: 300
      location: US
      priority: interactive
      job_retry: None  # <-- And here
